# Generated by Django 3.0.6 on 2020-05-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='images/python_logo.jpg', upload_to='images/'),
        ),
    ]
